name: Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: "Install Python dependencies"
        run: pip install -e ".[test]"
      - name: "Unit tests"
        run: pytest --junitxml=unit-results.xml
      - uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: unit-test-results
          path: unit-results.xml

  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    needs: unit-tests
    env:
      SIGRID_REPORTGENERATORDEMO_TOKEN: ${{ secrets.SIGRID_REPORTGENERATORDEMO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: "Install Python dependencies"
        run: pip install -e ".[test]"
      - name: "Integration tests"
        run: pytest -m integration --junitxml=integration-results.xml
      - uses: actions/upload-artifact@v4
        if: (!cancelled())
        with:
          name: integration-test-results
          path: integration-results.xml